apiVersion: v1
baseDomain: aelicie.xyz
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 1
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: ocp-dev
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  gcp:
    projectID: optical-mode-277107
    region: asia-southeast1
publish: External
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3BrY2hvbzFocW50ZHlxa2piMDJ5a2VvOHNwcWtxZHh5czpDWEhGTklBU0hPWDBWRUVTMldMTUhTUExBUktLUzlVN0ZOSVFGSTREVzVFSUtSVkM2T1NXTFBTVlgxT1ZGQUYx","email":"pchoo@redhat.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3BrY2hvbzFocW50ZHlxa2piMDJ5a2VvOHNwcWtxZHh5czpDWEhGTklBU0hPWDBWRUVTMldMTUhTUExBUktLUzlVN0ZOSVFGSTREVzVFSUtSVkM2T1NXTFBTVlgxT1ZGQUYx","email":"pchoo@redhat.com"},"registry.connect.redhat.com":{"auth":"NTIzNzI2NTR8dWhjLTFIcU50ZHlxS2piMDJZa0VPOHNQcWtxRHh5czpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmpPRE5pTVRRM056ZzNOalEwTXpZNE9UZ3lZVFUzWXpOak9HRXdNRGMzTmlKOS5EeWRUbWpObk1fZ2hSWkZsWGxudXdIYzFGRVk1OWh1QV9LYjFCYlZKSEp0OGVpVDlNZ2xxTUU1RDhnUmE5eDNpYXJVQ0VqbUVVWkFueFVvMkZuM1d5YlVKMmdnc1FrcEl6VF9qd1p2VUtyckt3OW1jV1Y0TVNLcGVTQkFZNG1CM2pMaHJFanNhTnhTU3E2RGpVejh4TzNVWkVJZ3hyTmdBazhFaExEMHM4STdkdmw4bjV5NDBRejZtNHlLWnFoYXRVY2xKeUk4R1BLUm0xMUEzRmhBQzBlYkI5UWpqV25HS2R6V1BMVE41eEI3THM2QkJWWkhDc3N4MGxkS3g3TEtWXzA4OXhHSW1yenZkZVVXRDFNQTE4NDZNMEFCRkswcDBtbjZPN1d6NGpsT0ZEY1lfUUluc3hqdEN2dUR1ajhROEdmRlNHOEFTN3pZeFRKbTRyZklNbEptX0RXV1ZyZTB4V05yLWZ1OVVDeE1McFRWbUliN01JTHA4aGdGd1dwQ2VXemp3bExFWkFyeUNoSXQ5cFRMRk0yMENvV1RpRU1Ccmk3Wml4LWt3VkpWcFpUcGtqVnpMYkt2SVVrcEtUTkoxM0k2ZnF2Wms2ZnhuUTNoeFJZTFh4RE9Ia2RkcUNqUzh6ZS01MGJqNWxlSjZ4XzVRVW04dzVBLUZ1UUVNdXpUdWFqamdCZS0xSHNyVHdENjF6R0YxeUY3dUZZZ2tTbThIeU5CR2FjYk93M3hCT2g1cHExWERvN0NzbWstR1AzS3U5Q01wTm5GT0ExSWtEU1hXMTV4YWUyRTF3OHFBcmVDNWNnNjRZeHh4NVpLWFN2TWRXSjZrVkozbzhsTjdUQUN5WmtOMXNoQUpJRlRBQTZRZW9xZWJEX2dlNF9ZWGpXazd1ZnozTnFBMWZYTQ==","email":"pchoo@redhat.com"},"registry.redhat.io":{"auth":"NTIzNzI2NTR8dWhjLTFIcU50ZHlxS2piMDJZa0VPOHNQcWtxRHh5czpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmpPRE5pTVRRM056ZzNOalEwTXpZNE9UZ3lZVFUzWXpOak9HRXdNRGMzTmlKOS5EeWRUbWpObk1fZ2hSWkZsWGxudXdIYzFGRVk1OWh1QV9LYjFCYlZKSEp0OGVpVDlNZ2xxTUU1RDhnUmE5eDNpYXJVQ0VqbUVVWkFueFVvMkZuM1d5YlVKMmdnc1FrcEl6VF9qd1p2VUtyckt3OW1jV1Y0TVNLcGVTQkFZNG1CM2pMaHJFanNhTnhTU3E2RGpVejh4TzNVWkVJZ3hyTmdBazhFaExEMHM4STdkdmw4bjV5NDBRejZtNHlLWnFoYXRVY2xKeUk4R1BLUm0xMUEzRmhBQzBlYkI5UWpqV25HS2R6V1BMVE41eEI3THM2QkJWWkhDc3N4MGxkS3g3TEtWXzA4OXhHSW1yenZkZVVXRDFNQTE4NDZNMEFCRkswcDBtbjZPN1d6NGpsT0ZEY1lfUUluc3hqdEN2dUR1ajhROEdmRlNHOEFTN3pZeFRKbTRyZklNbEptX0RXV1ZyZTB4V05yLWZ1OVVDeE1McFRWbUliN01JTHA4aGdGd1dwQ2VXemp3bExFWkFyeUNoSXQ5cFRMRk0yMENvV1RpRU1Ccmk3Wml4LWt3VkpWcFpUcGtqVnpMYkt2SVVrcEtUTkoxM0k2ZnF2Wms2ZnhuUTNoeFJZTFh4RE9Ia2RkcUNqUzh6ZS01MGJqNWxlSjZ4XzVRVW04dzVBLUZ1UUVNdXpUdWFqamdCZS0xSHNyVHdENjF6R0YxeUY3dUZZZ2tTbThIeU5CR2FjYk93M3hCT2g1cHExWERvN0NzbWstR1AzS3U5Q01wTm5GT0ExSWtEU1hXMTV4YWUyRTF3OHFBcmVDNWNnNjRZeHh4NVpLWFN2TWRXSjZrVkozbzhsTjdUQUN5WmtOMXNoQUpJRlRBQTZRZW9xZWJEX2dlNF9ZWGpXazd1ZnozTnFBMWZYTQ==","email":"pchoo@redhat.com"}}}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCe6qi0wbm3i9rcU49rHY68bzDDPu5v9egNFANV/fsCqgWY/u2RNzM0USwlrn7NDzJ93JElw5FoHe6fuB+70JKFHvMUcCEERB82o/y5ia8nSvgdnMOfTG6G47RluVwEBDPfc28KGYjdmPh/7z9XCiGV5Bm/g1w3X7iXL6EmhCUNINsuqOOHPD3Knd7rcocJQ6Z2s6qP2UvISLDaR4EkONmUZUbl8mg3Xj5JZGU+WfWfqm0C8RvyKZZE2BJpzkdmXeHUhs3087+dwd5SEB5LqC/N5t72AaDUPskdcfQJPbFa9IGsg7xlVDmt8JYIg0O6/Ly/oLkVYVBfmplur5lNbYvRV+3uQ2FdN1TsCbrqcF5A5lcHIlhBqOgwd33fLiCxXjsbdV+/mLu1Hq8ZHT/t7GGm6yzo75lGm69HVBga3ZUPnte5xR1/0mcWJjkriMYmaReYtCFI2m/DIcTNYJfidk/fbCoB4RPdWBJKRJQffU9H3JsERhGA4/qTJADyqlpK8HKswO7tmZWKaqsoj7YN3qdWWlADTd13r0cRnvvhaBoBF8EP0qc8c3ZdcIXOBK3m+9UtOnjEWdXv7xGJk71DfVdlROqQw35JPNgqXAPJXQCXrmmufEKoQ8nwH0cA9eAPIC+QiKqU88OhhRRIk8qMuWQ+1YxhOjcJVA94JxrcxYVptw== pchoo@cs-6000-devshell-vm-92f8ba12-29e5-41fe-a652-9ff2ff188c43
